---
title: ""
---


<style type="text/css">
.body {
  text-align: justify;
  padding-top: 30px;
  padding-right: 30px;
  padding-left: 30px;"
}
</style>

<div class="body">

Hello! My name is Rosanna, I was born in St. Gallen Switzerland and moved to the U.S. during my childhood. Since then I have lived in Michigan and California. Having experienced semi-urban environments,
with each consecutive location having greater pollution problems, I became interested
in the human-environmental interface. While I originally wanted to express this interest
through architecture, I've come to be more intrigued by the larger system, exploring human-environmental interactions at various scales. 

I spent 2012 - 2016 completing a [B.S. in the College of Natural Resources](http://guide.berkeley.edu/undergraduate/degree-programs/conservation-resource-studies/), with a focus on water systems  engineering, and a [B.A. in the College of Environmental Design](http://guide.berkeley.edu/undergraduate/degree-programs/urban-studies/)
at the University of California, Berkeley. During this time I learned about how water moves through an ecosystem, its effect on that ecosystem, how we fight over water, extract water, have unequal access to safe water, pollutants found in water, and how urbanization has an influence on all of the above. I contributed to key research on storm inundations across all of California, sediment transport in the Everglades, and the urban heat island effect in Hong Kong. I spent four years learning about all the things I had been questioning and more.

Currently, I am a [Ph.D. candidate in Geography, Earth System Science](http://geography.berkeley.edu/graduate-studies/program-description/) (still at Berkeley). At the beginning of my doctoral studies, I took part in a two-year National Science Foundation [Data Science program](http://ds421.berkeley.edu/) and completed a Designated Emphasis in [Computational and Data Science and Engineering](https://citris-uc.org/initiatives/decse/) to build on my quantitaive analytical skills. Throughout my Ph.D. I've been studying various human-environmental systems - as well as operating systems and other technical components of computing - and overtime became greatly concered with development impacts on coral reefs. 

Coral reefs, nurseries to an estimated 25% of all marine life, are key to human and environmental prosperity. Provided my background in urban studies, combined with my hydrologist lens and multi-year experience with remote sensing, I found the most suitable contribution to the field of marine biology that I can provide in this context to be mapping out coastal development and quantifying the potential impacts it has on adjacent reefs. This is what I've been primarily working on for the past year: scrapping spatial information from the web, creating a pixel based land use classifier, and applying it accross the Pacific, all wrapped up in a data pipeline. I plan on completing my dissertation May 2021 and hope to further apply my human-environmental system domain knowledge and statistical skillset in addressing urban planning concerns.

</div>
