---
title: ""
---

<h3>Education</h3>
<hr>

<br>
<strong>University of California, Berkeley</strong><br>
<i>Graduate GPA: 3.93</i> <i style="float: right;">08/2016 - present</i>  <br>
<strong>Ph.D.</strong> Geography, Earth System Science<br>
<strong>Designated Emphasis:</strong> Computational and Data Science and Engineering <br>
<strong>NSF Research Traineeship Program:</strong> Data Sciences for the 21st Century <br>
<i>Undergraduate GPA: 3.56</i> <i style="float: right;"> 08/2012 - 05/2016</i> <br>
<strong>B.S.</strong> Conservation and Resource Studies, focus: Water Systems Engineering <br>
<strong>B.A.</strong> Urban Studies <br>

<br>
<h3>Awards and Grants</h3>
<hr>

<br>
NASA NSPIRES Fellowship  <i style="float: right;">09/2019 - 09/2022 </i> <br>
ISEECI Summer Research Grant <i style="float: right;"> 06/2018 - 08/2018 </i> <br>
EWJ Gateway Fellowship  <i style="float: right;">08/2016 - 05/2017 </i> <br>
NSF Research Traineeship Fellowship <i style="float: right;">06/2017 - 06/2018 </i> <br>
Hong Kong PhD Fellowship Scheme (did not accept) <i style="float: right;">08/2016 - 08/2019 </i> <br>
Berkeley Conference Travel Grant <i style="float: right;">12/2017 </i>  <br>

<br>
<h3>Select Coursework</h3>
<hr>
<br>

<strong>Graduate</strong>:
Statistical Models: Theory & Application -- Topics in Earth System Remote Sensing -- 
Statistics & Multivariate Data Analysis for Research -- Collaborative & Reproducible 
Data Science -- Advanced Topics in Computer Systems -- Interdisciplinary Research Methods: 
Environment, Society, & Global Change --  Complex Environmental Systems -- Numerical Methods 
for Environmental Flow Modeling

<strong>Undergraduate</strong>:
Civil & Environmental Engineering System Analysis -- The City: Theory & Methods
in Urban Studies -- Geographic Information Systems -- Environmental Problem Solving -- Water Chemistry --
Fluid Mechanics -- Linear Algebra and Differential Equations -- Introduction to Statistics -- Water in
Terrestrial Environments -- Introduction to Envrionmental Economics <br>

<br>
<h3>Skills</h3>
<hr>
<br>
<strong>Technical</strong>: Python, R, MATLAB, Git, LaTeX, ArcGIS, AdobePhotoshop, AutoCAD, C++, and
Google Earth Engine. Currently learning D3.js. <br>
<strong>Language</strong>: English, Swiss-German, and German.

<br>
<h3>Internships</h3>
<hr>
<br>

<strong>Cal Energy Corps: Urban Climate Study <i>NT, Hong Kong</i></strong> <i style="float: right;">06/2015 - 08/2015</i>
<br style="line-height: 9px" />
As part of the Cal Energy Corps internship program, semi-automated step in research process
for Edward Ng, at the Chinese University of Hong Kong.Wrote a MATLAB script and functions that 
semi-automated the process for calculating view factors of various enveloping structural 
and natural surfaces onto a central point from fisheye images. 
In the process of writing the code, I taught myself how to code and how to explain
code to the architecture majors that then used it. <br>

<br> 
<strong>Arndt Geiger Herrmann Architecture Firm <i>Zurich, Switzerland</i></strong> <i style="float: right;">06/2013 - 08/2013</i>
<br style="line-height: 9px" />
Designed interior features for an $8 million house on CAD software. 
Contributed to numerous projects via presentation preparation and CAD drawings.

<br>
<h3>Research</h3>
<hr>
<br>

<strong>Remote sensing for Coral Bleaching Prediction</strong> <i style="float: right;">06/2019 - present</i>
<br style="line-height: 9px" />
Detecting potential spatial determinants of coral bleaching using in-situ and remotely sensed data 
from across the Pacific Ocean. <br>

<br>
<strong>Comparing discrepancies between social vulnerability indicies associated with Superfund Sites based on varying methods of spatial overlay and resampling</strong> <i style="float: right;">09/2017 - present</i>
<br style="line-height: 9px" />
Analyzing perceived socially vulnerable groups at risk of superfund site failures based on
different methodologies used when combining the social data at the census block level with
superfund sites represented as spatial point files. 
Conducted with a fellow graduate student in the NSF Data Science Research program, Jacob Bukoski, as a capstone project for the program. <br>

<br>
<strong>Stochastic spatio-temporal modelling of marine benthic coverages as a function of herbivourous grazers, water quality, and coral demographics (Oxford, UK)</strong> <i style="float: right;">06/2016 - 07/2016</i>
<br style="line-height: 9px" />
In collaboration with Dr. Maria Bruna and Dr. Martin Robinson, spent five weeks over the summer 
at the University of Oxford creating a python model of marine benthic coverages to investigate  
meta-stability between ecological regime shifts. <br>

<br>
<strong>Fluvial Geomorphology, Everglades Study</strong> <i style="float: right;">07/2014 - 05/2015</i>
<br style="line-height: 9px" />
Research assistant for Laurel Larsen, professor in the Geography Department, UC Berkeley. 
Manipulating a provided MATLAB code to perform noise reduction on flow rate data that was then
used to determine bed shear stresses for calculating sediment transport.
Compared to observations from Acoustic Doppler Velocimeter (ADV) data, viewed via
Vectrino Profiler playback. <br>

<br>
<strong>Flood Inundation Simulations of the Bay Area and Sacramento Delta</strong> <i style="float: right;">03/2014 - 03/2015</i>
<br style="line-height: 9px" />
As a research assistant for prof. John Radke, prepared terrestrial spatial data used in
simulating the 100-year storm impact, at various predicted Sea-Level Rise stages, across California.  <br>
Gathered data through LiDar Analyst tools, & digitizing, and contacting local government agencies. <br>

<br>
<h3>Conference Talks</h3>
<hr>
<br>


<strong>International Coral Reef Symposium</strong> <i style="float: right;">July 2021</i>
<br style="line-height: 9px" />
*Spatiotemporal Investigation of Reef Resilience in the Pacific Ocean in the 2014-2017 Bleaching Events* <br>
<strong>Rosanna Neuhausler^1^</strong>, Laurel Larsen ^1^, and Mark Eakin ^2^ <br>
1. University of California, Berkeley, USA. <br>
2. National Oceanic and Atmospheric Administration<br>

<br>
<strong>2020 SIAM Conference on Mathematics of Planet Earth</strong> <i style="float: right;">INVITED August 2020</i>
<br style="line-height: 9px" />
*The effect of spatial patterns in phase shifts: a stochastic spatiotemporal investigation of coral reefs* <br>
<strong>Rosanna Neuhausler^1^</strong>, Martin Robinson ^2,3^, and Maria Bruna ^2,3^ <br>
1. University of California, Berkeley, USA. <br>
2. University of Oxford, Computer Science Department <br>
3. University of Oxford, Mathematical Institute <br>

<br>
<strong>AGU Ocean Sciences Meeting</strong> <i style="float: right;">February 2018</i>
<br style="line-height: 9px" />
*Satellites, Servers, and Spatial Overlay: A multifaceted workflow for investigating spatial determinants*  <br>
*of Coral Bleaching Trends across the Pacific* <br>
<strong>Rosanna Neuhausler^1^</strong>, Laurel Larsen ^1^, and Mark Eakin ^2^ <br>
1. University of California, Berkeley, USA. <br>
2. National Oceanic and Atmospheric Administration <br>

<br>
<strong>2019 SIAM Conference on Applications of Dynamical Systems</strong> <i style="float: right;">May 2019</i>
<br style="line-height: 9px" />
*An Integrated Approach to Coral-Algal Phase Shift Modeling: Numerical Methods Meets Data Science* <br>
<strong>Rosanna Neuhausler^1^</strong>, Martin Robinson ^2,3^, and Maria Bruna ^2,3^ <br>
1. University of California, Berkeley, USA. <br>
2. University of Oxford, Computer Science Department <br>
3. University of Oxford, Mathematical Institute <br>

<br>
<strong>AGU Ocean Sciences Meeting</strong> <i style="float: right;">February 2018</i>
<br style="line-height: 9px" />
*Assessing social vulnerabilities to potential Superfund site failures from coastal storm*  <br>
*surge in the United States* <br>
<strong>Rosanna Neuhausler^1^</strong>, Jacob Jean Bukoski^2^, and Adam Orford^3^. <br>
1. University of California, Berkeley, Department of Geography. <br>
2. University of California, Berkeley, Department of Environmental Science, Policy, and Management. <br>
3. University of California, Berkeley, Energy and Resources Group. <br>

<br>
<strong>European Coral Reef Symposium, Oxford, UK</strong> <i style="float: right;">December 2017</i>
<br style="line-height: 9px" />
*Stochastic spatio-temporal model of coral cover as a function of herbivorous grazers,*  <br>
*water quality, and coral demographics* <br>
<strong>Rosanna Neuhausler^1^</strong>, Martin Robinson ^2,3^, and Maria Bruna ^2,3^ <br>
1. University of California, Berkeley, USA. <br>
2. University of Oxford, Computer Science Department <br>
3. University of Oxford, Mathematical Institute <br>

<br>
<strong>Workshops on Big Data and Urban Informatics, Chicago, IL</strong> <i style="float: right;">August 2014</i>
<br style="line-height: 9px" />
*Planning for the Change: Mapping Sea Level Rise and Storm Inundation in Sherman Island Using 3Di*  <br>
*Hydrodynamic Model and LiDAR* <br>
Yang Ju^1^, Wei-Chen Hsu^1^, John D. Radke^1^, William L. Fourt^1^, Wei Lang^1^, Olivier Hoes^2^,  <br>
Howard Foster^1^, Gregory Biging^1^, Emery Roe^1^, Martine Schmidt-Poolman^2^, <strong>Rosanna Neuhausler^1^</strong>,  <br>
Amna Alruheil^1^ and William F. Maier^1^ <br>
1. University of California, Berkeley, USA. <br>
2. Delft University of Technology, Netherlands

<br>
<h3>Selected Publications</h3>
<hr>
<br>

Y. Ju, W. Hsu, J. Radke, W. Fourt, W. Lang, O. Hoes, H. Foster, G. Biging, M. Schmidt-Poolman,  <br>
R. Neuhausler, A. Alruheil, W. Maier. (2016)
<br style="line-height: 9px" />
*Planning for the Change: Mapping Sea Level Rise and Storm Inundation in Sherman Island*  <br>
Using 3Di Hydrodynamic Model and LiDAR. In: Thakuriah P., Tilahun N., Zellner M. (eds) Seeing  <br>
Cities Through Big Data. Springer Geography. Springer, Cham. 1.2K downloads on [link.spring.com](https://link.springer.com/chapter/10.1007/978-3-319-40902-3_18)

<br>
<h3>Leadership and Competition</h3>
<hr>
<br>

<strong>Geog40: Introduction to Earth System Science</strong><i style="float: right;">2018</i>
<i>Graduate Student Instructor</i>
<br style="line-height: 9px" />
Taught two 2-hour lab sections consisting of around 18 students each, creating and grading  <br>
assignments, creating midterm questions and holding office hours.<br>

<strong>University of Tokyo Data Science Boot Camp</strong><i style="float: right;">2018</i>
<i>Assistant Instructor</i> | 
<br style="line-height: 9px" />
Assisted in teaching data science to Ph.D. students from various humanities and natural science  <br>
departments at the University of Tokyo. The Boot Camp ran for two weeks and was cohosted by  <br>
Berkeley and the University of Tokyo’s Mathematics Institute.<br>

<strong>Sagehen Data Camp</strong> <i style="float: right;">2018</i>
<i>Organizer/Leader</i>
<br style="line-height: 9px" />
Leading a team of undergraduates to the UC Natural Reserve, Sagehen Creek Field Station, for  <br>
a week long data organizing, processing, and analyzing bootcamp as an effort to expose  <br>
students to field work and data science, as well as a revamping of the site.<br>

<strong>Cal EnviroTeam</strong> <i style="float: right;">2015</i> 
<i>Treasurer/Member</i> 
<br style="line-height: 9px" />
Designed a water filtration system to compete in the annual water treatment competition  <br>
at the ASCE Mid-Pacific Student Conference. <br>
As treasurer, was in charge of managing the organizations funds.<br>

<strong>Berkeley Water Group IdeaLab</strong> <i style="float: right;">2013 - 2014</i>
<i>Creative Director/Member</i> 
<br style="line-height: 9px" />
Forum for Berkeley-affiliated individuals from all departments to discuss water-related issues. <br>
Created posters for our biweekly meetings, which host speakers from water-related fields.<br>

<strong>Global Architecture Brigades</strong> <i style="float: right;">2012 - 2013</i>
<i>Member</i>
<br style="line-height: 9px" />
With Berkeley chapter, won rain harvest system design competition in fall 2012.<br>
Flew to Honduras with teammates to construct our design.<br>

<strong>Pioneer High School Track and Cross Country team</strong> <i style="float: right;">2008-2012</i>
<i>Co-captaion/Teammate</i> 
<br style="line-height: 9px" />
Led workouts, organized team events, motivated and supported teammates. <br>
Won states titles in 4 x 800 meter relay and regional titles in 5 kilometer and 800 meter races. <br>
Continuing to race in long distance races today. I finished first out of all the women in the  <br>
2016 Napa Wine Country Half Marathon and am training regularly with friends.

