---
title: ""
---
 
<style>

p{
padding-right: 20px;
padding-left: 20px;
}

</style>

<body>

<br>
<br>
<br>

<p>
Hello! My name is Rosanna, I am from St. Gallen Switzerland and moved to the U.S. during my childhood. Since then I have lived in Michigan and California. Having experienced semi-urban environments,
with each consecutive location having greater pollution concerns, I developed an interest
in the human-environmental interface. While originally wanting to express this interest
through architecture, I've come to recognize the importance of addressing such concerns through the system at large, exploring human-environmental interactions at various scales. 
</p>
<p>
I spent 2012 - 2016 completing a [B.S. in the College of Natural Resources](http://guide.berkeley.edu/undergraduate/degree-programs/conservation-resource-studies/), with a focus on water systems  engineering, and a [B.A. in the College of Environmental Design](http://guide.berkeley.edu/undergraduate/degree-programs/urban-studies/)
at the University of California, Berkeley. 
</p>
<p>
Currently, I am a [Ph.D. candidate in Geography, Earth System Science](http://geography.berkeley.edu/graduate-studies/program-description/) (still at Berkeley). At the beginning of my doctoral studies, I took part in a two-year National Science Foundation [Data Science program](http://ds421.berkeley.edu/) and completed a Designated Emphasis in [Computational and Data Science and Engineering](https://data.berkeley.edu/decdse) to build on my quantitaive analytical skills. Upon
completion of the Ph.D. Summer 2022, I will explore the intersection of hard sciences and expressionism through a
1-month art residency at [Atelier 11](http://www.lairarts.com/atelier-11.html) in Paris, applied to my dissertation on the impact of coastal
urbanization on coral reefs in Southeast Asia and Oceania.

</body>




